/*
 * generated by Xtext
 */
package aom.scripting.xs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XSUiModule extends aom.scripting.xs.ui.AbstractXSUiModule {
	public XSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
