/*
 * generated by Xtext
 */
package aom.scripting.xs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XSRuntimeModule extends aom.scripting.xs.AbstractXSRuntimeModule {

}
