/*
 * generated by Xtext
 */
package aom.scripting.xs;

import de.itemis.xtext.typesystem.ITypesystem;
import aom.scripting.xs.typesystem.XsTypesystem;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XSRuntimeModule extends aom.scripting.xs.AbstractXSRuntimeModule {
	public Class<? extends ITypesystem> bindITypestem() {
		return XsTypesystem.class;
	}
}


