/*
* generated by Xtext
*/
package aom.scripting.xs;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XSStandaloneSetup extends XSStandaloneSetupGenerated{

	public static void doSetup() {
		new XSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

