/*
 * generated by Xtext
 */
package aom.scripting.xs.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import aom.scripting.xs.ui.internal.XSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XSActivator.getInstance().getInjector(XSActivator.AOM_SCRIPTING_XS_XS);
	}
	
}
